config/routes.rb
Portfolio::Application.routes.draw do
  root                :to=> 'pages#home'
  match '/showcase',  :to=> 'pages#showcase'
  match '/education', :to=> 'pages#education'
  match '/exp',       :to=> 'pages#exp'
  match '/other',     :to=> 'pages#other'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # @modTime = File.mtime('../views/layouts/application.html.erb')
  def education
    @title = "Education"
  end

  def showcase
    @title = "Showcase"
  end

  def exp
    @title = "Work Experience"
  end

  def other
    @title = "Other"
  end
  
  def home
    @title = "About Me"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_contact_info.html.erb
<div id="contact_info">
	<div class="title">Contact</div>
	<span>
		<strong>LOCATION:</strong> <a href="http://g.co/maps/djngk" target="_blank">Brooklyn, NY</a><br />
		<strong>EMAIL:</strong> <a href="mailto:yusyang686@gmail.com">yusyang686@gmail.com</a><br />
		<strong>TEL:</strong> 347.985.0619 <br />
		<strong>GITHUB:</strong> <a href="http://www.github.com/vinc386" target="_blank">vinc386</a><br>
	</span>
</div>

app/views/layouts/_cv.html.erb
<a href="http://db.tt/MQMN1WPd">Resume</a>

app/views/layouts/_footer.html.erb
<div id="copyright">
	Copyright &copy; <%= link_to 'Vincent Yang', 'http://www.visitvincent.com'%> 2011-2012 power by  <a href="http://rubyonrails.org/" target="_blank">Ruby on Rails</a> and <a href="http://www.heroku.com/" target="_blank">Heroku</a>.
</div>

app/views/layouts/_nav.html.erb
<div id="nav">
	<ul>	
		<li><%= link_to "Home", root_path %></li> |
		<li><%= link_to "Education", education_path %></li>  |
		<li><%= link_to "Showcase", showcase_path %></li> |
		<li><%= link_to "Work Exp.", exp_path %></li> |
		<li><%= render "layouts/cv" %></li> | 
		<li><%= link_to "Other", other_path %></li>
	</ul>
</div>

app/views/layouts/_skills.html.erb
<div id="skills">
	<div class="title">Skills</div>
	<span>
		<strong>LANGUAGES</strong>: Ruby on Rails, HTML, CSS, JavaScript, jQuery, &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
		SQL(sqLite, mySQL, MS Access), Java <br/>
		<strong>SOFTWARE</strong>: Adobe CS5, MS Office, MS Projects, <a href="http://www.github.com/vinc386" target="_blank">git/Github</a><br/>
		<strong>OS</strong>: MS Windows, Mac OSX, Ubuntu
	</span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= stylesheet_link_tag "application", :media => 'screen'%>
	<%= javascript_include_tag "application" %>
	<%= favicon_link_tag 'favicon.ico'%>
	<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" %>
	<%= javascript_include_tag "http://cdnjs.cloudflare.com/ajax/libs/noisy/1.1/jquery.noisy.min.js" %>
	<!-- <%= javascript_include_tag "rails" %> -->
	<%= csrf_meta_tag %>
	<title>Vincent Yang | <%=  @title%></title>
	<!-- google analytics -->
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-28239083-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>
	<style>
		body{
			background:#ddd;
			margin:0px;
			font-family:Verdana;
			font-size:8pt;
		}
		body a:link{
			text-decoration:none;
			color:#297cab;/*blue*/
		}
		body a:visited{
			color:#297cab;
		}
		body a:hover{
			color:#ea1;
		}
		strong{
			font-family:Helvatica;
		}
		#body_container{
			width:750px;
			height:100%;
			margin:auto;
		}
		#topbar{
			width:100%;
			height:30px;
			margin:0px 0px 10px 0px;
			border-bottom:1px #777 dotted;
		}
		#nav ul{			
			list-style:none;
			float:right;
			margin:10px 0 5px 0;
		}
		#nav li{
			display:inline;
		}
		#page_title{
			height:45px;
			width:100%;
			margin-top:15px;
			font-family:Tahoma;
			font-size:24pt;
		}
		#content_container{
			height:500px;
			width:100%;
			overflow:auto;
			font-family:Freesans;
		}
		#content{
			margin:20px 0px 0px 20px;
			font-family:Tahoma;
			font-size:10pt;
		}
		#content div.title{
			font-weight:bold;
			font-family:Gerogia;
			font-size:12pt;
			text-decoration:underline;
		}
		#content span.details{
			position:relative;
			top:5px;
			left:10px;
		}
		#content a{
			font-size:9pt;
			font-weight:bold;
			text-decoration:underline;
		}
		#footer_container{
			width:100%;
			height:150px;
			margin-top:5px;
			border-top:1px #777 dotted;
			border-bottom:1px #777 dotted;
			line-height:130%;
		}
		#footer_container div>span{
			padding-left:10px;
			padding-top:10px;
			display:block;
		}
		#footer_container .title{
			font-family:Helvatica;
			font-size:18pt;
			margin:5px 0px;
		}
		#skills_wrapper{
			width:400px;
			height:100%;
			float:left;
		}
		#contact_wrapper 
		{
			width:250px;
			height:100%;
			float:left;
		}
		#logo_wrapper{
			width:100px;
			height:100%;
			float:left;
			position:relative;
			top:20px;
			right:15px;
		}
		#skills, #contact_info{
			padding:20px 10px 10px 20px;
		}
		#copyright{
			height:20px;
			width:100%;
			text-align:center;
			padding-top:3px;
		}
	</style>
</head>
<body>		
	<div id="body_container">
		<div id="topbar">
			<%= render "layouts/nav"%>
		</div>
		<div id ="page_title">
			<%= @title %>
		</div>
		<div id="content_container">
			<div id="content">
				<%= yield %>
			</div>
		</div>
		<div id="footer_container">
			<div id="skills_wrapper">
				<%= render "layouts/skills" %>
			</div>
			<div id="contact_wrapper">
				<%= render "layouts/contact_info" %>
			</div>
			<div id="logo_wrapper"><%= link_to image_tag("logo.png", :id =>'logo'), '/'%></div>
		</div>
		<div id="copyright"><%= render "layouts/footer"%></div>
	</div>
<!-- add noise to background -->
<script>
	$('body').noisy({
	    'intensity' : 0.754, 
	    'size' : '100', 
	    'opacity' : 0.070, 
	    'fallback' : '', 
	    'monochrome' : true
	}).css('background-color', '#ddd');
</script>
<!-- change logo opacity with mouse hover -->
<script>
		// $('#content_container').css('background', 'white').fadeTo('10', '0.2');
		$(document).ready(function(){
			$('#logo').fadeTo('1', '0.4');
		});
		$('#logo').hover(function(){
			$(this).fadeTo('1', '1');
		});
		$('#logo').mouseleave(function(){
			$(this).fadeTo('1', '0.4');
		});

</script>
</body>
</html>

app/views/pages/education.html.erb
<div id="education">
	<div class="title">State University of New York at Stony Brook</div>
	<span class="details">
		Stony Brook, NY<br>
		<ul>
			<li>B.S degree in <strong>Information System</strong> & B.S. degree in <strong>Technological System Management</strong></li>
			<li>Dean's list from Fall 2007 to Fall 2009</li>
			<li>Graduated in May 2011, GPA 3.3</li>
		</ul><br>
	</span>
	<div class="title">Lower East Side Preparatory High School</div>
	<span class="details">
		New York, NY<br>
		<ul>
			<li>Dean's list from Fall 2005 to Spring 2007</li>
			<li>Graduated in May 2007, GPA 3.8</li>
		</ul>
	</span>
</div>

app/views/pages/home.html.erb
<div style="font-size:48pt;">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>

app/views/pages/role.html.erb
<ul>
	<dl>
		<dt>
		- Ruby on Rails Apprentice, <small><i>about 1 year</i></small>
		</dt><br />
			<dd>
				<a href="http://github.com/vinc386">My Github: </a><br />
				<tt>It serves as my RoR sandbox, therefore some applications you see there may not be well-built or even completed</tt>
			</dd>
				<br />
			<dd>
				<a href="http://rubrik.heroku.com/users/login">Rubrik: </a><br />
				<tt>A e-Learning platform that provides easy class enrollment, assignment and exam distribution, and academic record handling</tt>
			</dd>
				<br />
			<dd>
				<a href="http://goo.gl/CUO2o">JMap: </a><br />
				<tt>A simple interactive map project built with JQuery </tt>
			</dd>
				<br />
			<dd>
				<a href="http://www.visitvincent.com">VisitVincent.com: </a><br />
				<tt>My personal website which is also built using RoR </tt>
			</dd>
				<br />
				<hr />
				<br />
		<dt>
		- Junior Project Coordinator, <small><i>about 1 year</i></small>
		</dt>
		<br />
			<dd>
				<tt>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
					</tt>
			</dd>
			<br />
			<hr />
			<br />
		<dt>
		- Amateur Digital Photographer, <small><i>for 2+ year</i></small>	
		</dt>
		<br />
			<dd>
				<tt>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
					</tt>
			</dd>
		<br />
		<dd>
			<tt>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
				</tt>
		</dd>
	</dl>
</ul>